### ISSUE TITLE
Use notie.alert with an enum for types?

### ISSUE THREAD

**Issue by skvale** [jaredreich/notie.js#28]
I find it easier to remember enums than numbers.

README.md
```javascript
notie.alert(notie.types.SUCCESS, 'Success!', 1.5);
notie.alert(notie.types.WARNING, 'Warning<br><b>with</b><br><i>HTML</i><br><u>included.</u>', 2);
notie.alert(notie.types.ERROR, 'Error.', 2.5);
notie.alert(notie.types.INFO, 'Information.' 2);
```

notie.js
```javascript
var types = {
    SUCCESS: 1,
    WARNING: 2,
    ERROR: 3,
    INFO: 4
}
.....
return {
   alert: alert,
   confirm: confirm,
   input: input,
   types: types
};
```

**Comment by skvale** [comment]
[This fork](https://github.com/skvale/notie.js)

**Comment by jaredreich** [comment]
Thanks for the feedback though it's definitely easier to type "2" than "notie.types.WARNING". Feel free to pursue this on your forks!

**Comment by skvale** [comment]
Sounds good, thanks for considering it.  It would still work to type either `2` or `notie.types.WARNING` .

**Comment by jaredreich** [comment]
Ah I see thank you for explaining. Perhaps I will still implement this. Thanks again.

**Comment by skvale** [comment]
Let me know if you would like me to open a pull request.

**Comment by connorjburton** [comment]
I think enums would be a good idea along with simple integers, just thinking if there is a way to reference them without going through notie.types.X

**Comment by jaredreich** [comment]
I'm still not convinced how notie.type.success is easier to remember than "1". It's unlikely there'll ever be more than 4 categories (sucess/error/warning/info) so is remembering that 1-4 are your choices really not sufficient? Just my $0.02

**Comment by InstanceOfMichael** [comment]
> It's unlikely there'll ever be more than 4 categories (sucess/error/warning/info)

I'll definitely be nuking my fork with up to 16 variations.
