### ISSUE TITLE
Input demo should focus text field

### ISSUE THREAD

**Issue by simevidas** [jaredreich/notie.js#33]
On https://jaredreich.com/projects/notie.js/, pressing the Input button opens an overlay, but the input element in the dialog is not automatically focused. This unnecessarily forces the user to click/tap on said input element to start using it.

Btw, I think this functionality should be provided by the library, automatically. Also, please see if you can integrate keyboard accessibility; after activating the Confirm/Input buttons, the dialog should be focused and the focus order should be trapped inside said dialog (so that the user doesn’t accidentally focus other page elements that are behind the overlay).

**Comment by jaredreich** [comment]
Great suggestions, will look into this, thank you.
