### ISSUE TITLE
"Confirm" demo should not disappear when tapped or clicked somewhere else other than cancel 

### ISSUE THREAD

**Issue by rahulchrty** [jaredreich/notie.js#38]
In the demo "Conform" appears as an overlay and it has Yes and Cancel (or we can use "No" which sounds more mandatory in some cases) option. The "Conform notie" should not get disappear when tap or click somewhere else other than "Cancel" option. 

https://jaredreich.com/projects/notie.js/

In cases if a conformation is mandatory and the user tap somewhere else the "notie" will disappear and the user may not able to conform it again :)

**Comment by filfat** [comment]
+1

**Comment by jaredreich** [comment]
You shouldn't say "it should not dissappear" as this is your opinion. The correct action would be to make this a settable option for whether the backdrop click triggers a hide or not. I will implement this eventually, thanks for the feedback.
