### ISSUE TITLE
Dismiss alert programmatically

### ISSUE THREAD

**Issue by roccomuso** [jaredreich/notie.js#57]
How do we dismiss an alert programmatically?

Is this possible? Do I miss something on the documentation?

**Comment by jaredreich** [comment]
You haven't missed anything - this feature isn't present.
Good idea though, will implement.

**Comment by razagill** [comment]
Any progress on this issue? If not, are you willing to accept a PR for this?

**Comment by vyachkonovalov** [comment]
I'm using this workaround
```javascript
document.querySelector('#notie-alert-outer').click()
```
so, the feature implementation might be as short as the click handler
https://github.com/jaredreich/notie.js/blob/master/notie.js#L179-L183

**Comment by roccomuso** [comment]
@jaredreich I'm working on this PR. But let me know if you're still active on this repo. If not you should add any other contributor and remove the old ones.

**Comment by jaredreich** [comment]
I am active but I've travelling for a while - sorry for the delay. I have this already incorporated into a huge update in the works for notie.js
Thanks!

**Comment by roccomuso** [comment]
@jaredreich so, no need to make a PR? let me know.

**Comment by jaredreich** [comment]
Yeah I don't think so I have it integrated already, thanks very much for the effort though!
