### ISSUE TITLE
worked wrong

### ISSUE THREAD

**Issue by lichunqiang** [jaredreich/notie.js#61]
I used with ajax submit:

in **beforeSubmit** called `notie.alert(4, 'Starting...', 1)`

in ** success** called `notie.alert(1, 'success')`

the success callback called, but the alert was not display...

**Comment by jaredreich** [comment]
This is a specific case for your application and I can't replicate it - for me, notie always replaces the currently displayed notie and correctly shows. Sorry, good luck.

**Comment by lichunqiang** [comment]
@jaredreich Pls see this example:
http://lichunqiang.github.io/tests/notie.html
