### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lichunqiang** [jaredreich/notie.js#64]
@jaredreich Pls see this example:
http://lichunqiang.github.io/tests/notie.html

it happens on the server response quickly

**Comment by jaredreich** [comment]
If I close your issue #61, please don't re-open a new one.
You'll have to fork and fix yourself for your specific single-case scenario.

**Comment by lichunqiang** [comment]
If i can solve this, i will do. but not.
any help or suggestion to solve this will be happy, but not the rejection.
