### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by LordMidi** [jaredreich/notie.js#67]
Would be good to provide a minfied version of notie.js within the repo. All of my other bower vendor dependencies provide a minified version so I can concat all of them together in one file. If I want to use notie.js I have to do a minification task only for notie.js.

Thanks

**Comment by raphaelparent** [comment]
+1

**Comment by roccomuso** [comment]
+1

**Comment by jaredreich** [comment]
future commits will include a minified file, thanks
