### ISSUE TITLE
Remove styles from JS, add CSS classes instead

### ISSUE THREAD

**Issue by gnicol-bzh** [jaredreich/notie.js#70]
Hello,

To allow users to easily customize the design of Notie.js, I suggest to remove every styles from JS and use a CSS instead - SCSS would be even better. Then use JS to add/remove CSS classes (not styles) from HTML. 

An external CSS is easier to customize and override than DOM style attributes; it does not require "!important" in front of each CSS property value, you can change CSS without editing JS, ...

**Comment by jaredreich** [comment]
Thanks for the suggestion though this kind of negates the whole point of notie being pure javascript with no dependencies (only one file to include)... hence the name notie.js

If the majority of users agreed with this of course it'd be worth changing, though not sure if that's the case.

Either way thanks for the input though I most likely won't perform this huge modification.
