### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jamescauson** [jaredreich/notie.js#8]
Hey @jaredreich ,

Anychance you could put this on bower / npm for people to use? 

I think it will increase the usage of notie.js

Thanks

**Comment by jaredreich** [comment]
Definitely, will do this soon. Thanks for the suggestion!

**Comment by jaredreich** [comment]
Little update - someone else just took the npm name 'notie' about a week ago for a different, more obscure module. That sucks haha. We'll see what I can come up with. I can either ask them to change the name or just use notie-js
